export default {
  ADD: 'Add',
  ACTION: 'Action',
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  CLONE: 'Clone',
  COPY: 'Copy',
  COPY_OF: 'copy_of_{{name}}',
  DELETE: 'Delete',
  DISCARD_CHANGES: 'Discard Changes?',
  DESCRIPTION: 'Description',
  EDIT: 'Edit',
  NO: 'No',
  NO_KEEP_CHANGES: 'No, Keep Changes',
  NONE: 'None',
  NAME: 'Name',
  YES_SAVE: 'Yes, Save',
  YES_DELETE: 'Yes, Delete',
  NOTIFICATION_MEDIUMS: 'Notification Mediums',
  GLOBAL_SETTINGS: 'Global Settings',
  SYSTEM_ADMINISTRATION: 'System Administration',
  RESET_ALL_FIELDS: 'Yes, Reset All Fields',
  INPUT_NAME_MAX_CHAR: 'Name must be between 1 and 30 characters',
  SHOW_TEXT: 'Show',
  HIDE_TEXT: 'Hide',
  NOTIFICATION_MEDIUM_MODULE: {
    APPLICATION: 'Application',
    ADD_NOTIFICATION_MEDIUM: 'Add Medium',
    ADD_NOTIFICATION_MEDIUM_FAILURE_MESSAGE:
      'The notification medium could not be created. {{reason}}.',
    ADD_NOTIFICATION_MEDIUM_SUCCESS_MESSAGE: 'The notification medium is created.',
    CANCEL_DIALOG_MESSAGE: 'The changes to the notification medium will not be saved.',
    CLONE_NOTIFICATION_MEDIUM_TOOLTIP: 'Clone notification medium',
    DELETE_NOTIFICATION_MEDIUM_DIALOG_MESSAGE:
      'The notification medium will be deleted permanently.',
    DELETE_NOTIFICATION_MEDIUM_DIALOG_TITLE: 'Delete Notification Medium?',
    DELETE_NOTIFICATION_MEDIUM_FAILURE: 'The Notification Medium could not be deleted. {{reason}}.',
    DELETE_NOTIFICATION_MEDIUM_FAILURE_MESSAGE:
      'The notification medium could not be deleted. It is used in one or more Configuration.',
    DELETE_NOTIFICATION_MEDIUM_SUCCESS: 'The Notification Medium deleted successfully.',
    DELETE_NOTIFICATION_MEDIUM_TOOLTIP: 'Delete notification medium',
    EDIT_NOTIFICATION_MEDIUM: 'Edit Medium',
    EDIT_NOTIFICATION_MEDIUM_FAILURE_MESSAGE:
      'Changes to the notification medium could not be saved. {{reason}}.',
    EDIT_NOTIFICATION_MEDIUM_SUCCESS_MESSAGE: 'Changes to the Notification Medium are saved.',
    ERROR_SUBMITTING_FORM: 'Error submitting form',
    NOTIFICATION_MEDIUM_LOADING_MESSAGE: 'Loading Notification Mediums Data...',
    NOTIFICATION_MEDIUM_DELETE_LOADING_MESSAGE: 'Deleting Notification Medium Data...',
    NOTIFICATION_MEDIUM_NAME_VALIDATION: 'Please enter name of the notification medium.',
    NOTIFICATION_MEDIUM_NAME_EXIST_VALIDATION: 'Notification medium name already exist.',
    NOTIFICATION_MEDIUM_SEARCH_PLACEHOLDER: 'Search in Medium Name',
    SAVE_NOTIFICATION_MEDIUM_DIALOG_TITLE: 'Save Notification Medium?',
    VIEW_NOTIFICATION_MEDIUM_ERROR_MESSAGE: 'Unable to get notification medium data',
    MEDIUM_NAME: 'Medium Name',
    MEDIUM: 'Medium',
    MANAGE_NOTIFICATION_MEDIUM_TOOLTIP: 'Manage notification medium',
    SELECT_APPLICATION: 'Select Application',
    CANCEL_MODAL_PRIMARY_BTN: 'Yes, Discard Without Saving',
    OPTIONAL: 'Optional',
    DESCRIPTION_LENGTH_MAX: 'Description can not be longer than 255 characters.',
    NOTIFICATION_MEDIUM_APPLICATION_VALIDATION:
      'Please select application of the notification medium.',
    SENDER_EMAIL_LABEL: 'Sender E-mail ID',
    SLACK_URL_LABEL: 'Slack URL',
    SLACK_TOKEN_LABEL: 'Auth Token for the Application BOT',
    NOTIFICATION_MEDIUM_EMAIL_VALIDATION: 'Please enter valid email-id of the sender.',
    NOTIFICATION_MEDIUM_URL_VALIDATION: 'Slack URL is required.',
    NOTIFICATION_MEDIUM_TOKEN_VALIDATION: 'Slack Token is required.',
    SLACK_URL_LENGTH_MAX: 'Slack URL can not be longer than 100 characters.',
    SLACK_TOKEN_LENGTH_MAX: 'Slack Token can not be longer than 100 characters.',
    INVALID_SLACK_URL: 'Please enter valid Slack Url.',
    INVALID_SLACK_TOKEN: 'Please enter valid Slack Token.',
    INVALID_EMAIL: 'Please enter valid Email.',
    RESET_NOTIFICATION_MESSAGE: 'All fields are replaced with saved values.',
    RESET_NOTIFICATION_MEDIUM_DIALOG_MESSAGE:
      'All fields will be replaced with the saved notification medium.',
    RESET_NOTIFICATION_MEDIUM_DIALOG_TITLE: 'Reset Notification Medium?',
    SAVE_NOTIFICATION_MEDIUM_DIALOG_MESSAGE: 'Changes to the notification medium will be saved.',
    SEPARATE_TEAMS_TEXT: '*Add separate medium instances for each teams channel.',
    TEAMS_LINK: 'How to create web hook URL for Teams Channel',
    TEAMS_URL_LABEL: 'Webhook URL of Channel',
    NOTIFICATION_MEDIUM_TEAMS_URL_VALIDATION: 'Channel Web hook URL is required.',
    INVALID_TEAMS_URL: 'Please enter valid Teams webhook Url.',
    ERROR_LOADING_NOTIFICATION_LIST: 'Could not load notification mediums. {{reason}}.',
    SLACK_ATTRIBUTE_TEXT: `*Please ensure that the user's slack ID is same as the user's email address. This is required for the notifications to work`,
    EMAIL_TEXT: 'Email',
    SLACK_TEXT: 'Slack',
    TEAMS_TEXT: 'Teams',
    MANAGE_NOTIFICATION: 'Manage notification medium',
    CLONE_NOTIFICATION: 'Clone notification medium',
    DELETE_NOTIFICATION: 'Delete notification medium',
    DENIED_CLONE_NOTIFICATION: 'Access denied for clone notification medium',
    DENIED_DELETE_NOTIFICATION: 'Access denied for delete notification medium',
    SLACK_LINK: 'Learn Enabling interactions with bots here',
  },
  RESET: 'Reset',
  SAVE: 'Save',
};
