export default {
  ACTION: 'Action',
  APPROVE: 'Approve',
  APPROVAL: 'Approval',
  APPROVERS: 'Approver(s)',
  CLOSE: 'Close',
  COPY: 'Copy',
  CANCEL: 'Cancel',
  COMMENTS: 'Comments',
  DESCRIPTION: 'Description',
  FOR: 'for',
  NONE: 'None',
  LOADING: 'Loading...',
  OPTIONAL: 'Optional',
  MY_SECRETS: 'My Secrets',
  MY_APPROVALS_AND_REQUEST_MODULE: {
    APPROVALS_LOADING: 'My Approvals Loading',
    APPROVE_REQUEST: 'Approve Request?',
    APPROVAL_STATUS: 'Approval status',
    APPROVED_BY: 'Approved By',
    APPROVED_ON: 'Approved On',
    EXPIRED_ON: 'Expired On',
    FETCHING_APPROVALS: 'Fetching approvals details',
    FETCHING_REQUESTS: 'My Requests Loading',
    PERMISSION_GRANTED: 'permission will be granted to',
    PERMISSION_DENIED: 'permission will be denied to',
    REJECT_REQUEST: 'Reject Request?',
    REQUESTED_ON: 'Requested On',
    REQUESTED_BY: 'Requested By',
    REQUEST_APPROVED: 'The Request is approved',
    REQUEST_REJECTED: 'The Request is rejected',
    REQUEST_NOT_APPROVED: 'Could not approve the request. {{reason}}.',
    REQUEST_NOT_REJECTED: 'Could not reject the request. {{reason}}.',
    REQUEST_DATE: 'Request Date',
    REJECTED_BY: 'Rejected By',
    REJECTED_ON: 'Rejected On',
    SEARCH_RESOURCE: 'Search in Resource',
    SEARCH_NOT_SUPPORTED: 'Search is not supported on this screen',
    SEARCH_REQUEST: 'Search Resource',
    MESSAGE_EXPIRED: 'This request is expired due to no action from approvers',
    MESSAGE_APPROVED: 'This request is approved by {{userName}}',
    MESSAGE_REJECTED: 'This request is rejected by {{userName}}',
    APPROVAL_EXPIRED_MESSAGE: 'Validity expired',
    MANAGE_REQUEST_TITLE: 'Manage Request',
    APPROVE_REQUEST_TOOLTIP: 'Approve Request',
    REJECT_REQUEST_TOOLTIP: 'Reject Request',
  },
  RESOURCE: 'Resource',
  REJECT: 'Reject',
  SECRETS_MODULE: {
    ALL_SECRETS: 'All Secrets',
    COPIED_TO_CLIPBOARD: 'Copied to clipboard',
    COPY_ALL: 'Copy All',
    ERROR_LOADING_SECRET: 'Could not load secret. {{reason}}.',
    ERROR_LOADING_SECRETS_LIST: 'Could not load secrets. {{reason}}.',
    HIDE: 'Hide',
    LOADING_NODE_DATA: 'Loading Node...',
    APPROVAL_MESSAGE: '{{userName}} has requested {{accessType}} access for secret {{secretName}}',
    MY_APPROVALS: 'My Approvals',
    MY_REQUESTS: 'My Requests',
    MY_SECRETS: 'My Secrets',
    NO_ACTIONS_AVAILABLE: 'No Actions Available',
    SECRET_LOADING_MESSAGE: 'Loading Secrets...',
    SECRET_DETAILS_LOADING_MESSAGE: `Loading Secret...`,
    SECRETS_NAME_HEADER: 'Secret Name',
    SECRETS_PATH_HEADER: 'Path',
    SECRETS_SEARCH_PLACEHOLDER: 'Search in Secret Name',
    SECRETS_STATUS_HEADER: 'Status',
    SHOW: 'Show',
    VIEW_SECRET_TOOLTIP: 'View secret',
    WAITING_FOR_APPROVAL: 'Waiting for Approval',
    WAITING_FOR_APPROVAL_PRIMARY_BUTTON: 'Ok',
    WAITING_FOR_APPROVAL_DIALOG_MESSAGE: 'The request is waiting for approval.',
    NOTIFIED_TEXT: 'You will be notified about the status of this request.',
    TRACK_TEXT: 'You can also track request in "My Requests" section.',
    VIEW_ACTION: 'View Secret',
    SEND_REQUEST_BUTTON: 'Send Request',
    NEED_APPROVAL: 'You need approval to',
    APPROVAL_REQUEST_SENT: 'Approvers :',
    SENDING_APPROVAL_REQUEST: 'Sending approval request...',
    JUSTIFICATION_TEXT: 'Justification',
    JUSTIFICATION_LENGTH_MAX: 'Justification can not be longer than 255 characters.',
    APPROVAL_REQUIRED_TEXT: 'Approval Required',
    JUSTIFICATION_REQUIRED: 'Justification is required.',
    AVAILABLE_TEXT: 'Available',
    ACCESS_REQUEST_SENT_MESSAGE: 'Access request is sent for approval.',
    LOADING_APPROVERS_DETAILS: 'Loading approvers details...',
    APPROVAL_PENDING_TEXT: 'Approval Pending',
    APPROVAL_DENIED_TEXT: 'Access Denied',
    ALREADY_APPROVED: 'Request is already approved',
    ALREADY_REJECTED: 'Request is already rejected',
    ALREADY_EXPIRED: 'Request Expired',
    VIEW_SECRET: 'View Secret',
    ACCESS_PROFILE: 'Access Profile',
    REJECTED_STATUS: 'Rejected',
    APPROVED_STATUS: 'Approved',
    TIMEOUT_STATUS: 'Request Expired',
    APPROVE_SECRET_ACTION_MSG:
      '{{actionName}} permission will be granted to {{userName}} for {{resource}}',
    REJECT_SECRET_ACTION_MSG:
      '{{actionName}} permission will be denied to {{userName}} for {{resource}}',
    NONE_TEXT: 'None',
    DETAILS_FAILURE_MESSAGE: 'The details could not be fetched. {{reason}}',
  },
  VAULT_DETAILS_FETCHING_MESSAGE: 'Fetching secret details...',
  JUSTIFICATION: 'Justification',
  YES: 'Yes',
  YES_DELETE: 'Yes, Delete',
  YES_DISABLE: 'Yes, Disable',
  YES_ENABLE: 'Yes, Enable',
  YES_SAVE: 'Yes, Save',
  YES_DISCARD: 'Yes, Discard Without Saving',
  YES_APPROVE: 'Yes, Approve',
  YES_REJECT: 'Yes, Reject',
};
