export const active = 'active';

export const UsersType = {
  USERS_REQUEST: 'USERS_REQUEST',
  USERS_LOADING: 'USERS_LOADING',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USERS_FAILURE: 'USERS_ERROR',
};

export const GroupsType = {
  GROUPS_REQUEST: 'GROUPS_REQUEST',
  GROUPS_LOADING: 'GROUPS_LOADING',
  GROUPS_SUCCESS: 'GROUPS_SUCCESS',
  GROUPS_FAILURE: 'GROUPS_FAILURE',
};

export const ServiceIdentitiesType = {
  SERVICE_IDENTITY_REQUEST: 'SERVICE_IDENTITY_REQUEST',
  SERVICE_IDENTITY_LOADING: 'SERVICE_IDENTITY_LOADING',
  SERVICE_IDENTITY_SUCCESS: 'SERVICE_IDENTITY_SUCCESS',
  SERVICE_IDENTITY_FAILURE: 'SERVICE_IDENTITY_FAILURE',
};

export const TokensType = {
  TOKENS_REQUEST: 'TOKENS_REQUEST',
  TOKENS_LOADING: 'TOKENS_LOADING',
  TOKENS_SUCCESS: 'TOKENS_SUCCESS',
  TOKENS_FAILURE: 'TOKENS_FAILURE',
};
