import { translate } from '../../../../externalization';

export const pageTitle = translate('MY_SECRETS');

export const MyRequestsDataTypes = {
  OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',
  MY_REQUESTS_LIST_REQUEST: 'MY_REQUESTS_LIST_REQUEST',
  MY_REQUESTS_LIST_LOADING: 'MY_REQUESTS_LIST_LOADING',
  MY_REQUESTS_LIST_SUCCESS: 'MY_REQUESTS_LIST_SUCCESS',
  MY_REQUESTS_LIST_FAILURE: 'MY_REQUESTS_LIST_FAILURE',
  MY_REQUESTS_LIST_SEARCH_TERM_UPDATE: 'MY_REQUESTS_LIST_SEARCH_TERM_UPDATE',
  MY_REQUESTS_LIST_LOAD_MORE_REQUEST: 'MY_REQUESTS_LIST_LOAD_MORE_REQUEST',
  MY_REQUESTS_LIST_LOAD_MORE_LOADING: 'MY_REQUESTS_LIST_LOAD_MORE_LOADING',
  MY_REQUESTS_LIST_LOAD_MORE_SUCCESS: 'MY_REQUESTS_LIST_LOAD_MORE_SUCCESS',
  MY_REQUESTS_LIST_LOAD_MORE_FAILURE: 'MY_REQUESTS_LIST_LOAD_MORE_FAILURE',
};

export const UsersType = {
  USERS_REQUEST: 'USERS_REQUEST',
  USERS_LOADING: 'USERS_LOADING',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USERS_FAILURE: 'USERS_FAILURE',
};

export const TagsType = {
  USER_TAGS_REQUEST: 'USER_TAGS_REQUEST',
  USER_TAGS_LOADING: 'USER_TAGS_LOADING',
  USER_TAGS_SUCCESS: 'USER_TAGS_SUCCESS',
  USER_TAGS_FAILURE: 'USER_TAGS_FAILURE',
};

export const tableColumns = {
  requestedOn: translate('MY_APPROVALS_AND_REQUEST_MODULE.REQUESTED_ON'),
  actionType: translate('ACTION'),
  resourceName: translate('RESOURCE'),
  justification: translate('JUSTIFICATION'),
  approvers: translate('APPROVERS'),
  approvalStatus: translate('MY_APPROVALS_AND_REQUEST_MODULE.APPROVAL_STATUS'),
};

export const translatedStrings = {
  noneValue: translate('NONE'),
  myRequestsSearchText: translate('MY_APPROVALS_AND_REQUEST_MODULE.SEARCH_NOT_SUPPORTED'),
  loadingMessage: translate('LOADING'),
};

export const active = 'active';
