export const classes = {
  addEntityModalLabel: 'add-entity-modal-label',
  addEntityModalValue: 'add-entity-modal-value',
  addEntityInputSpacing: 'add-entity-input-spacing',
  actionWrapperPill: 'action-wrapper-pill',
  viewActionPill: 'view-action-pill',
  roleDetailsModalFieldWrapper: 'role-details-modal-field-wrapper',
  roleDetailsModalLabel: 'role-details-modal-label',
  roleDetailsModalValue: 'role-details-modal-value',
  roleValueModalContainer: 'role-value-modal-container',
  roleLabelModalContainer: 'role-label-modal-container',
  rolePermissionWrapper: 'role-permission-wrapper ',
  addEntitySearchField: 'add-entity-search-field',
  viewRoleEntityModalScroll: 'view-role-entity-modal-scroll',
  stepperMainContainer: 'roles-tab-add-policy-outer-container',
  formLoaderModal: 'form-loader-modal',
  entityModalScroll: 'add-existing-role-modal-container',
  addPolicyFieldWrapper: 'add-policy-field-wrapper',
  addPolicyFieldValueWrapper: 'add-policy-field-value-wrapper',
  addPermissionButtonsWrapper: 'add-permission-buttons-wrapper',
  addRoleTablePermissions: 'add-role-table-permissions',
  permissionActionItems: 'permission-action-items',
  permissionActionDelete: 'permission-action-delete',
  permissionActionView: 'permission-action-view',
  entityTableSpacing: 'entity-table-spacing',
};
