export const GetMetadataType = {
  GET_METADATA_REQUEST: 'SM_POLICY_GET_METADATA_REQUEST',
  GET_METADATA_LOADING: 'SM_POLICY_GET_METADATA_LOADING',
  GET_METADATA_COMPLETE: 'SM_POLICY_GET_METADATA_COMPLETE',
  GET_METADATA_FAILURE: 'SM_POLICY_GET_METADATA_FAILURE',
};
