export const ConsumerListTypes = {
  CONSUMER_LIST_REQUEST: 'CONSUMER_LIST_REQUEST',
  CONSUMER_LIST_LOADING: 'CONSUMER_LIST_LOADING',
  CONSUMER_LIST_SUCCESS: 'CONSUMER_LIST_SUCCESS',
  CONSUMER_LIST_FAILURE: 'CONSUMER_LIST_FAILURE',
  CONSUMER_LIST_RESET: 'CONSUMER_LIST_RESET',
};
