import { translate } from '../../../packages/policy-management/externalization';

export const CloneFetchUserType = {
  FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_USER_REQUEST_LOADING: 'FETCH_USER_REQUEST_LOADING',
  FETCH_USER_REQUEST_SUCCESS: 'FETCH_USER_REQUEST_SUCCESS',
  FETCH_USER_REQUEST_FAILURE: 'FETCH_USER_REQUEST_ERROR',
};
export const CloneFetchGroupType = {
  FETCH_GROUP_REQUEST: 'FETCH_GROUP_REQUEST',
  FETCH_GROUP_REQUEST_LOADING: 'FETCH_GROUP_REQUEST_LOADING',
  FETCH_GROUP_REQUEST_SUCCESS: 'FETCH_GROUP_REQUEST_SUCCESS',
  FETCH_GROUP_REQUEST_FAILURE: 'FETCH_GROUP_REQUEST_ERROR',
};
export const CloneFetchTokenType = {
  FETCH_TOKEN_REQUEST: 'FETCH_TOKEN_REQUEST',
  FETCH_TOKEN_REQUEST_LOADING: 'FETCH_TOKEN_REQUEST_LOADING',
  FETCH_TOKEN_REQUEST_SUCCESS: 'FETCH_TOKEN_REQUEST_SUCCESS',
  FETCH_TOKEN_REQUEST_FAILURE: 'FETCH_TOKEN_REQUEST_ERROR',
};
export const CloneFetchServiceIdentityType = {
  FETCH_SERVICE_IDENTITY_REQUEST: 'FETCH_SERVICE_IDENTITY_REQUEST',
  FETCH_SERVICE_IDENTITY_REQUEST_LOADING: 'FETCH_SERVICE_IDENTITY_REQUEST_LOADING',
  FETCH_SERVICE_IDENTITY_REQUEST_SUCCESS: 'FETCH_SERVICE_IDENTITY_REQUEST_SUCCESS',
  FETCH_SERVICE_IDENTITY_REQUEST_FAILURE: 'FETCH_SERVICE_IDENTITY_REQUEST_ERROR',
};
export const CloneUsersType = {
  CLONE_USERS_REQUEST: 'CLONE_USERS_REQUEST',
  CLONE_USERS_LOADING: 'CLONE_USERS_LOADING',
  CLONE_USERS_SUCCESS: 'CLONE_USERS_SUCCESS',
  CLONE_USERS_FAILURE: 'CLONE_USERS_ERROR',
};

export const CloneGroupsType = {
  CLONE_GROUPS_REQUEST: 'CLONE_GROUPS_REQUEST',
  CLONE_GROUPS_LOADING: 'CLONE_GROUPS_LOADING',
  CLONE_GROUPS_SUCCESS: 'CLONE_GROUPS_SUCCESS',
  CLONE_GROUPS_FAILURE: 'CLONE_GROUPS_FAILURE',
};

export const CloneServiceIdentitiesType = {
  CLONE_SERVICE_IDENTITY_REQUEST: 'CLONE_SERVICE_IDENTITY_REQUEST',
  CLONE_SERVICE_IDENTITY_LOADING: 'CLONE_SERVICE_IDENTITY_LOADING',
  CLONE_SERVICE_IDENTITY_SUCCESS: 'CLONE_SERVICE_IDENTITY_SUCCESS',
  CLONE_SERVICE_IDENTITY_FAILURE: 'CLONE_SERVICE_IDENTITY_FAILURE',
};

export const CloneTokensType = {
  CLONE_TOKENS_REQUEST: 'CLONE_TOKENS_REQUEST',
  CLONE_TOKENS_LOADING: 'CLONE_TOKENS_LOADING',
  CLONE_TOKENS_SUCCESS: 'CLONE_TOKENS_SUCCESS',
  CLONE_TOKENS_FAILURE: 'CLONE_TOKENS_FAILURE',
};

export const ClonePolicyType = {
  CLONE_POLICY_REQUEST: 'CLONE_POLICY_REQUEST',
  CLONE_POLICY_LOADING: 'CLONE_POLICY_LOADING',
  CLONE_POLICY_SUCCESS: 'CLONE_POLICY_SUCCESS',
  CLONE_POLICY_FAILURE: 'CLONE_POLICY_FAILURE',
};

export const CloneNotificationType = {
  OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',
  CLOSE_NOTIFICATION: 'CLOSE_NOTIFICATION',
};

export const ClonePermissionDetailsType = {
  CLONE_PERMISSION_DETAILS_REQUEST: 'CLONE_PERMISSION_DETAILS_REQUEST',
  CLONE_PERMISSION_DETAILS_LOADING: 'CLONE_PERMISSION_DETAILS_LOADING',
  CLONE_PERMISSION_DETAILS_SUCCESS: 'CLONE_PERMISSION_DETAILS_SUCCESS',
  CLONE_PERMISSION_DETAILS_FAILURE: 'CLONE_PERMISSION_DETAILS_FAILURE',
};

export const ClonePermissionActionsType = {
  CLONE_PERMISSION_ACTIONS_REQUEST: 'CLONE_PERMISSION_ACTIONS_REQUEST',
  CLONE_PERMISSION_ACTIONS_LOADING: 'CLONE_PERMISSION_ACTIONS_LOADING',
  CLONE_PERMISSION_ACTIONS_SUCCESS: 'CLONE_PERMISSION_ACTIONS_SUCCESS',
  CLONE_PERMISSION_ACTIONS_FAILURE: 'CLONE_PERMISSION_ACTIONS_FAILURE',
  CLONE_PERMISSION_ACTIONS_RESET: 'CLONE_PERMISSION_ACTIONS_RESET',
};

export const clonePermissionsListType = {
  RECURSIVE_CLONE_PERMISSIONS_LIST_REQUEST: 'RECURSIVE_CLONE_PERMISSIONS_LIST_REQUEST',
  RECURSIVE_CLONE_PERMISSIONS_LIST_LOADING: 'RECURSIVE_CLONE_PERMISSIONS_LIST_LOADING',
  RECURSIVE_CLONE_PERMISSIONS_LIST_SUCCESS: 'RECURSIVE_CLONE_PERMISSIONS_LIST_SUCCESS',
  RECURSIVE_CLONE_PERMISSIONS_LIST_FAILURE: 'RECURSIVE_CLONE_PERMISSIONS_LIST_FAILURE',
  RECURSIVE_CLONE_PERMISSIONS_LIST_RESET: 'RECURSIVE_CLONE_PERMISSIONS_LIST_RESET',
  RECURSIVE_CLONE_PERMISSIONS_LIST_LOADING_DISABLE:
    'RECURSIVE_CLONE_PERMISSIONS_LIST_LOADING_DISABLE',
};

export const cloneRolesListType = {
  RECURSIVE_CLONE_ROLES_LIST_REQUEST: 'RECURSIVE_CLONE_ROLES_LIST_REQUEST',
  RECURSIVE_CLONE_ROLES_LIST_LOADING: 'RECURSIVE_CLONE_ROLES_LIST_LOADING',
  RECURSIVE_CLONE_ROLES_LIST_SUCCESS: 'RECURSIVE_CLONE_ROLES_LIST_SUCCESS',
  RECURSIVE_CLONE_ROLES_LIST_FAILURE: 'RECURSIVE_CLONE_ROLES_LIST_FAILURE',
  RECURSIVE_CLONE_ROLES_LIST_RESET: 'RECURSIVE_CLONE_ROLES_LIST_RESET',
  RECURSIVE_CLONE_ROLES_LIST_LOADING_DISABLE: 'RECURSIVE_CLONE_ROLES_LIST_LOADING_DISABLE',
};

export const CloneRolesDetailsType = {
  CLONE_ROLES_DETAILS_REQUEST: 'CLONE_ROLES_DETAILS_REQUEST',
  CLONE_ROLES_DETAILS_LOADING: 'CLONE_ROLES_DETAILS_LOADING',
  CLONE_ROLES_DETAILS_SUCCESS: 'CLONE_ROLES_DETAILS_SUCCESS',
  CLONE_ROLES_DETAILS_FAILURE: 'CLONE_ROLES_DETAILS_FAILURE',
};

export const LoadPolicyDataType = {
  CLONE_LOAD_POLICY_REQUEST: 'CLONE_LOAD_POLICY_REQUEST',
  CLONE_LOAD_POLICY_LOADING: 'CLONE_LOAD_POLICY_LOADING',
  CLONE_LOAD_POLICY_SUCCESS: 'CLONE_LOAD_POLICY_SUCCESS',
  CLONE_LOAD_POLICY_FAILURE: 'CLONE_LOAD_POLICY_FAILURE',
  CLONE_LOAD_POLICY_RESET: 'CLONE_LOAD_POLICY_RESET',
  OPEN_NOTIFICATION: 'OPEN_NOTIFICATION',
  CLONE_LOAD_POLICY_JSON_REQUEST: 'CLONE_LOAD_POLICY_JSON_REQUEST',
  CLONE_LOAD_POLICY_JSON_LOADING: 'CLONE_LOAD_POLICY_JSON_LOADING',
  CLONE_LOAD_POLICY_JSON_SUCCESS: 'CLONE_LOAD_POLICY_JSON_SUCCESS',
  CLONE_LOAD_POLICY_JSON_FAILURE: 'CLONE_LOAD_POLICY_JSON_FAILURE',
  CLONE_LOAD_POLICY_JSON_RESET: 'CLONE_LOAD_POLICY_JSON_RESET',
};

export const translatedStrings = {
  policyCreatedSuccessMessage: translate('POLICIES_MODULE.ADD_POLICY_SUCCESS'),
  inlineType: translate('INLINE'),
  preDefinedType: translate('PRE_DEFINED'),
  loadingPolicy: translate('POLICIES_LOADING'),
  addingPolicy: translate('POLICIES_MODULE.ADDING_POLICY'),
  errorGetRolesList: (reason) => translate('POLICIES_MODULE.ERROR_GET_ROLE_LIST', { reason }),
  errorGetPermissionsList: (reason) =>
    translate('POLICIES_MODULE.ERROR_GET_PERMISSION_LIST', { reason }),
  warningGetRolesList: (reason) => translate('POLICIES_MODULE.WARNING_GET_ROLE_LIST', { reason }),
  warningGetPermissionsList: (reason) =>
    translate('POLICIES_MODULE.WARNING_GET_PERMISSION_LIST', { reason }),
  errorGetPolicyData: (reason) =>
    translate('POLICIES_MODULE.VIEW_POLICY_ERROR_MESSAGE_WITH_REASON', { reason }),
};
export const cloneNamePrefix = 'copy_of_';
export const dummyDate = '01/01/1970';
export const dateSearchCharacter = '-';
export const errorNotificationTime = 3000;
